services:
  db:
    image: postgres:16
    container_name: sicier-bd
    environment:
      POSTGRES_USER: sicier
      POSTGRES_PASSWORD: sicier
      POSTGRES_DB: sicier
    ports:
      - "5432:5432"
    volumes:
      - sicier_data:/var/lib/postgresql/data
    networks:
      - sicier_net

  backend:
    build:
      context: ../sicier
      dockerfile: Dockerfile
    container_name: sicier-app
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/sicier
      DATASOURCE_USERNAME: sicier
      DATASOURCE_PASSWORD: sicier
      SPRING_SECURITY_JWT_PRIVATE_KEY: super-secret-key-change-me
      SPRING_SECURITY_USER_GENERATOR: sicier-app
    ports:
      - "8080:8080"
    networks:
      - sicier_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: peticiones-frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8080/sicier/api/v1
    ports:
      - "5173:5173"
    networks:
      - sicier_net

networks:
  sicier_net:

volumes:
  sicier_data:
