services:
  db:
    image: postgres:16
    container_name: sicier-db
    environment:
      POSTGRES_USER: sicier
      POSTGRES_PASSWORD: sicier
      POSTGRES_DB: sicier
    ports:
      - "5432:5432"
    volumes:
      - sicier_data:/var/lib/postgresql/data
      - ./db/init-users.sql:/docker-entrypoint-initdb.d/01-init-users.sql:ro

  backend:
    image: brayam223/sicier:latest
    container_name: sicier-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sicier
      SPRING_DATASOURCE_USERNAME: sicier
      SPRING_DATASOURCE_PASSWORD: sicier
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_SECURITY_JWT_PRIVATE_KEY: super-secret-key-change-me
      SPRING_SECURITY_USER_GENERATOR: sicier-app
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SERVER_ERROR_INCLUDE_EXCEPTION: "true"
      SERVER_ERROR_INCLUDE_STACKTRACE: always
    ports:
      - "8080:8080"

  frontend:
    image: brayam223/peticiones-frontend:latest
    container_name: sicier-frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080/sicier/api/v1
    ports:
      - "5173:80"

volumes:
  sicier_data:
