services:
  db:
    image: postgres:16
    container_name: sicier-db
    environment:
      POSTGRES_USER: sicier
      POSTGRES_PASSWORD: sicier
      POSTGRES_DB: sicier
    ports:
      - "5432:5432"
    volumes:
      - sicier_data:/var/lib/postgresql/data

  backend:
    image: brayam223/sicier:latest
    container_name: sicier-backend
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/sicier
      DATASOURCE_USERNAME: sicier
      DATASOURCE_PASSWORD: sicier
    ports:
      - "8080:8080"

  frontend:
    image: brayam223/peticiones-frontend:latest
    container_name: sicier-frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080/sicier/api/v1
    ports:
      - "5173:80"

volumes:
  sicier_data:
